### ISSUE TITLE
Can't write on root files

### ISSUE THREAD

**Issue by vmihalachi** [SpazeDog/rootfw#2]
Hi, I can get this code working. Nothing happens to the files but the operations doesn't give any expeptions. 

```
if (RootFW.connect()) {
           FileWriter writer = RootFW.getFileWriter("some_file_path", Boolean.FALSE);
           writer.write(newContent);
           writer.flush();
           writer.close();
}
```

Can you help me?

**Comment by dbergloev** [comment]
Sure, but can you give me a path to where you are trying to write? Android's protection is specific to the location. It would help me setup a correct testing environment that I can use to locate that issue.

**Comment by vmihalachi** [comment]
I am trying to edit the build.prop file. 
If I am correct it is located in the Root folder so the path is /build.prop

Anyway I have tried also with another file located in the same folder but this time created by me.

**Comment by vmihalachi** [comment]
Forgot to say that the same code applied to a file located in data/data/an_app_package/shared_prefs will make the file empty. When you open it you see that is has zero length and no text in it.

**Comment by dbergloev** [comment]
There is your problem. /system is mounted read-only. However the kernel will return successful when trying to write to it. That is why no exception is thrown. Do this instead. 

``` java
if (RootFW.connect()) {
    // Create a `Disk` instance that points to `/system`
    Disk disk = RootFW.getDisk("/system");

    // Make /system Read/Write
    disk.mount( new String[]{"rw"} );

    FileWriter writer = RootFW.getFileWriter("some_file_path", false);
    writer.write(newContent);
    writer.flush();
    writer.close();

    // Make /system Read-Only again
    disk.mount( new String[]{"ro"} );
}
```

**Comment by dbergloev** [comment]
I will checkout the empty file issue. The FileWriter is not meant to empty a file. 

However, you did change `FALSE` to `TRUE` in your second argument when trying in shared_prefs? If you parse `FALSE`, it will overwrite the file and it should be empty. 

``` java
// This will overwrite the file and the content will be deleted
FileWriter writer = RootFW.getFileWriter("some_file_path", FALSE);

// This will not delete the content in the file, it will just put new content after the existing content
FileWriter writer = RootFW.getFileWriter("some_file_path", TRUE);
```

**Comment by vmihalachi** [comment]
I understand that the old content will be deleted and that is fine.
However the new content is not written so the file results empty.

**Comment by dbergloev** [comment]
Yes, but is this also a problem if you write to /data?

**Comment by vmihalachi** [comment]
Just tried this

```
if (RootFW.connect()) {
                        // Create a `Disk` instance that points to `/system`
                        Filesystem.Disk disk = RootFW.getDisk(uri.getParentFolder());

                        // Make /system Read/Write
                        disk.mount( new String[]{"rw"} );

                        FileWriter writer = RootFW.getFileWriter(uri.getFilePath(), false);
                        writer.write(newContent);
                        writer.flush();
                        writer.close();

                        // Make /system Read-Only again
                        disk.mount( new String[]{"ro"} );
                    }


// uri.getParentFolder() is the parent folder of the file
// uri.getFilePath() is the file path
```

With a file located in data/data/package_name/shared_prefs and the first time it worked but the second it erased all the data of the file.

**Comment by vmihalachi** [comment]
Retried and if I do this operation the first time it erases the file content the second saves the new content. Seems pretty random to me. Don't know what may be the cause.

**Comment by dbergloev** [comment]
``` java
if (RootFW.connect()) {
    Disk systemPart = RootFW.getDisk("/system");
    systemPart.mount( new String[]{"rw"} );

    try {
        FileWriter writer = RootFW.getFileWriter("/system/testfile.txt", false);
        writer.write("Line 1\n");
        writer.write("Line 2\n");
        writer.flush();
        writer.close();

    } catch (IOException e) {}

    RootFW.disconnect();
}
```

Tried running this 5 times and there was nothing wrong. The content is deleted and the new content is added (In other words, the file does not change). 

Maybe it is your toolbox/busybox version, or your shell. I have had shells that acted differently, but can't see why this should be a problem. This is all handled by `cat` which is a pretty stable binary/command. 

But you could try to clear your logcat (`adb logcat -c`) and then get a log while you run that code (`logcat | busybox grep -i rootfw`) <<--- run from device shell

**Comment by vmihalachi** [comment]
Is there a way to make the file readable and writable?
Should this work?

```
file.changeAccess(-1, -1, 777);
```

**Comment by dbergloev** [comment]
Yes that will make a file Read/Write/Executable. But remember that after Android 4.4, and especially Android 5 has strict SELinux security. It will not always work by changing permissions. For example if you change `/data/data/com.some.app/shared_prefs/somefile.xml` to `666`, other apps will have read access, but they will not be able to write to the file, even though it has been changed to world-writeable. This is because SELinux stops anyone from writing to other applications files. The permissions does not mater as SELinux does not care about that.

**Comment by vmihalachi** [comment]
```
if (RootFW.connect()) {
                       String message;
                        File file = RootFW.getFile(filePath);

                        int permission = file.getDetails().permission();
                        message = ""+permission;

                        file.changeAccess(-1, -1, 666);

                        permission = RootFW.getFile(filePath).getDetails().permission();
                        message += "\n"+permission;
}
```

Then it is strange that after that message is that?

```
600
600
```

**Comment by dbergloev** [comment]
Depends on what file you are changing. `/system` is still read-only, so if you are trying to change permissions on something like `/system/build.prop`, it will not work until you remount the partition.

**Comment by vmihalachi** [comment]
Stil not working, I am starting to think that is my phone. 
I have lollipop installed and using the a root checker app I saw that everything was ok.
Will change my rom and update you if something changes! 
Thanks for the help! :+1:

**Comment by dbergloev** [comment]
There was a small issue in `changeAccess`. It has been fixed: https://github.com/SpazeDog/rootfw/commit/983a4532eed23179d8e18f8021cb2042711ef810

**Comment by dbergloev** [comment]
And just added a small change more. Not sure if this fixes anything else, but it fixed an issue on a specific type of shell: https://github.com/SpazeDog/rootfw/commit/8232e9fe2f52a7d363a9d7e16491181549979bc8

**Comment by vmihalachi** [comment]
The first fix has resolved the problem that the permission won't change. 
Can say anything for the second at the moment since I am trying to reset the phone and install a new rom.

**Comment by vmihalachi** [comment]
Ok, I tested your code and it works properly

```
if (RootFW.connect()) {
    Disk systemPart = RootFW.getDisk("/system");
    systemPart.mount( new String[]{"rw"} );

    try {
        FileWriter writer = RootFW.getFileWriter("/system/testfile.txt", false);
        writer.write("Line 1\n");
        writer.write("Line 2\n");
        writer.flush();
        writer.close();

    } catch (IOException e) {}

    RootFW.disconnect();
}
```

-But- If I add this line after the catch it will not work and the file won't be changed.

```
systemPart.mount(new String[]{"ro"} );
```

Aside from that if I put this code in my app the dialog for superuser permission appears everytime (and with this new rom twice) while on other apps like solid explorer if I want to change the file no dialog will appear. Do you think that is fixable?

**Comment by dbergloev** [comment]
The FileWriter and FileReader works just like normal Readers and Writers. They provide a constant stream either in or out. This means that while a file is open, that shell cannot be used for anything else, like executing shell commands and such. It would block RootFW. Because of this, they use their own shell per file. This allows you to open multiple files at once, and at the same time continue using RootFW for other things. But it also means that each file will request a new root connection. 

Depending on what you are using these for, you could simply use something more simple like `File.read()`, `File.readOneLine()` and `File.write()`. Just get a `File` instance by calling `RootFW.getFile("file/path")`. These are for simpler reads and writes and do not open new shells to do it. They use your existing connection. 

The point with the FileWriter and FileReader, is that they can be used when you have to parse a Reader or Writer to another class. But if you are writing from your own class, there is no need to use them as you can simply use the `File` class instead.

**Comment by vmihalachi** [comment]
Ok, thanks!
From my point of view this issue can be closed but I suggest you if can to write in the Wiki page how to correctly write on files are are located in readable folders like system.

**Comment by vmihalachi** [comment]
For me the code worked well but for this user not so. 
He got an error message, do you know what it can be?
See this link http://forum.xda-developers.com/android/apps-games/app-turbo-editor-text-editor-t2832016/post59673540

**Comment by dbergloev** [comment]
Most people know that /system is read-only. The Wiki explains how RootFW works, it is not a guide into the inner works of Android.

**Comment by dbergloev** [comment]
Yes, you are trying to check `wasSuccessfull()` on a `NULL` object. Instead do

``` java
if (result != null && result.wasSuccessfull()) {
```

**Comment by vmihalachi** [comment]
But I didn't try to check for result.
The code was simply that in a try catch block

```
if (RootFW.connect()) {
                        Filesystem.Disk systemPart = RootFW.getDisk(uri.getParentFolder());
                        systemPart.mount(new String[]{"rw"});

                        File file = RootFW.getFile(uri.getFilePath());
                        file.write(newContent);

                        RootFW.disconnect();
                    }
```

**Comment by dbergloev** [comment]
Okay, maybe some where in the library I am making that mistake. I will check the related files.

**Comment by vmihalachi** [comment]
I'll search too.
Can it be the line 593 of the file File.java?

<pre><code>
for (String line : input) {
                        String escapedInput = oPatternEscape.matcher(line).replaceAll("\\\\$1");
                        Attempts attempts = mShell.createAttempts("echo '" + escapedInput + "' " + redirect + " '" + path + "' 2> /dev/null");
                        
                        if (!(status = attempts.execute().wasSuccessful())) {
                            break;
                        }
                        
                        redirect = ">>";
                    }
</code></pre>

**Comment by dbergloev** [comment]
https://github.com/SpazeDog/rootfw/commit/7e2755759888f58d86adc26979405a9de3c25e00 Well that is at least the most possible location

If you want me to test that thing, I have several devices with different Android versions for my own testing purposes. And I know how to debug, unlike most regular users.

**Comment by vmihalachi** [comment]
Well, tell me what you need and I'll give you all :)
The app I am developing is Turbo Editor https://github.com/vmihalachi/turbo-editor
That is the file where I do the save operation. https://github.com/vmihalachi/turbo-editor/blob/e399a217e591eed120c9022818cfcbd683279d71/libraries/sharedCode/src/main/java/sharedcode/turboeditor/task/SaveFileTask.java

**Comment by dbergloev** [comment]
To begin with, just provide an app with the fix I just added to RootFW. Then I will try to use them on all my test devices and see if any of them fails. I have test devices with Android 2.3, 4.0, 4.1, 4.4 and 5.0

**Comment by vmihalachi** [comment]
Ok, here is the link to the apk. https://www.dropbox.com/s/cu7118sner8jo9e/app-release.apk
The user had a Nexus 7 running 5.1, SE policy set to permissive, busybox and supersu set to auto grant

**Comment by dbergloev** [comment]
Well I can't test on 5.1, but the changes from 5.0 should not make any difference in this case. Root is running outside of SELinux. 

It works fine on the devices that I have (Except for Android 2.3 of cause), because it is not supported. But the rest works without issues. 

B.t.w. You should check the result from `File.write()`. It does not throw exceptions, it simply returns `TRUE` or `FALSE`. Like I said, it was made for simple fast writing, so I wanted to avoid having try/cache for it.

**Comment by vmihalachi** [comment]
I have changed a bit the write method to make it return a Result. I have sent the user with Android 5.1 the new update and the Result says that the command number is 3 and result code is 255. Does it help somehow?

**Comment by dbergloev** [comment]
Yes. 255 is the general error number for Toolbox. And the command number is the number of attempts. 

``` java
// Command number 1
echo 'Your content' >> 'the file'       // failed

// Command number 2
busybox echo 'Your content' >> 'the file'       // failed

// Command number 3
toolbox echo 'Your content' >> 'the file'       // failed
```

Why it fails them all I don't know. For that you need to get a log from him. RootFW logs everything, so the error message is in he's logcat some where. 

EDIT:

If you have changed it to return the result, you can just get the error message from there. The `Result` class is an extended `Data` container which contains an array of all the lines from the command. It will have all of the error lines. 

Look here for info on the `Data` container https://spazedog.github.io/rootfw/RootFW4-Docs/com/spazedog/lib/rootfw4/containers/Data.html

**Comment by vmihalachi** [comment]
Hi, the user has sent me a complete log.
Maybe it could help https://drive.google.com/file/d/0B4M1eQ8oIVUoWTJnTzVnMUtZSkE/view

**Comment by dbergloev** [comment]
Sadly no. 

```
03-25 20:40:56.840 D/com.spazedog.lib.rootfw4.Shell(21177): execute: Executing the command 'toolbox echo 'the test' > '/system/Untitled.txt' 2> /dev/null'
```

Most of RootFW redirects error messages to `/dev/null` to avoid using resources handling the output. You will have to change the RootFW code in `File.write()` and remove the `2> /dev/null` part so that errors are printed to `stdin`.

**Comment by dbergloev** [comment]
However I do think that I know what the problem is. Most Kitkat ROM's has `RO` set directly on the block device. I would think that this also goes for Android 5.0 and 5.1. This means that just remounting it as `RW` is not enough. It also needs to be changed on the block device. RootFW does this automatically, but your users busybox version does not support this. 

```
03-25 20:40:56.800 D/com.spazedog.lib.rootfw4.Shell(21177): execute: Executing the command 'busybox blockdev --setrw '/dev/block/platform/sdhci-tegra.3/by-name/APP' 2> /dev/null'
03-25 20:40:56.802 D/com.spazedog.lib.rootfw4.Shell(21177): execute: The command finished with the result code '127'
```

It does not have the `blockdev` command. I think he needs to update the busybox version.

**Comment by vmihalachi** [comment]
OK, the user updated busybox and now it works! Thanks for the help!

**Comment by dbergloev** [comment]
Glad to hear
